### ISSUE TITLE
Alert banner `govukButton` display with raw HTML contents

### ISSUE THREAD

**Issue by toomore** [alphagov/notifications-admin#4505]
Hi,

There are some issues in the alert banner when a user wants to delete the templates.

![image](https://user-images.githubusercontent.com/121504/207234187-52e6b41f-fb08-4ae7-89b0-2cd692e5902d.png)

https://github.com/alphagov/notifications-admin/blob/a22439ef6d0881f6c59bfacd67112fc28553ba6f/app/templates/components/banner.html#L27-L32

The default element will [be `button`](https://github.com/LandRegistry/govuk-frontend-jinja/blob/main/govuk_frontend_jinja/templates/components/button/macro.html#L19), but we use HTML code as button value. Therefore, the button will show all the raw codes as text on the button.

We could remove the HTML code to revise the problem:

``` python
 {{ govukButton({
   "text": "" if thing else delete_button,
   "html": delete_button + " ‘" + thing + "’" if thing else "", 
   "name": "delete", 
   "classes": "govuk-button--warning govuk-!-margin-top-2", 
 }) }} 
```
![image](https://user-images.githubusercontent.com/121504/207234845-ce273650-c86d-4ec5-b8bb-a55a21e87871.png)

Thanks~

**Comment by leohemsted** [comment]
Hi @toomore,

Thanks for raising! I'm not entirely sure what's happening with your setup - it's perfectly valid to have a `span` inside a `button` within the HTML spec, and modern browsers should appropriately render that. Indeed, testing this locally and on our production system, this code works fine as intended and the span is correctly rendered. We don't want the template name to be visible since the template name's already mentioned at the top of the banner, however, we want screen readers to give full context when reading out the button text, so we add the template name within a `govuk-visually-hidden` css class.

I'd suggest ensuring you have an up to date browser, have updated your govuk-frontend-jinja python repo and govuk-frontend repo to the latest version (and rebuilt css/js with `npm run build`),

While I was investigating this I did notice and fix an XSS vulnerability with this component, so if you've forked notifications-admin I'd encourage you to ensure you've got the most recent version.

As a final note, this repository was not designed with outside use in mind, rather, this is a codebase we've written for our own platform (https://www.notifications.service.gov.uk/) and is public since we're committed to [coding in the open](https://www.gov.uk/service-manual/technology/making-source-code-open-and-reusable) where possible. As such, we won't always be able to prioritise investigating issues raised if they do not impact our production system. If you do find other issues or concerns feel free to raise them, but I cannot promise we'll be able to work with you to solve every single one.

Many thanks,

Leo
