### ISSUE TITLE
Need to create a .babelrc file for gulp to run

### ISSUE THREAD

**Issue by pixeltrix** [alphagov/notifications-admin#74]
Trying to build the frontend for the first time I ran into this problem:

```
[15:12:55] Requiring external module babel-core/register
/Users/andyw/Repositories/alphagov/notifications-admin/gulpfile.babel.js:24
gulp.task('copy:govuk_template:template', () => gulp.src('bower_components/gov
                                           ^
SyntaxError: Unexpected token )
```

Which is obviously gulp choking on the ES6 syntax. To fix it I added a `.babelrc` file as [suggested here][1]:

``` json
{
  "presets": ["es2015"]
}
```

You should probably add a note about this to the README or commit the file so that others don't get tripped up.

[1]: https://markgoodyear.com/2015/06/using-es6-with-gulp/

**Comment by quis** [comment]
@pixeltrix Thanks for noticing. Assuming this is something that happens if you’re not using version 5 of Node (which we [do recommend in the README](https://github.com/alphagov/notifications-admin/blob/7c246ba3acb212a38b1eb84d832f7cefa505d0e1/README.md#building-the-frontend)).

But adding the `.babelrc` file can’t hurt; I’ve added a pull request here: #75
